### ISSUE TITLE
Couldn't run due to open CV error

### ISSUE THREAD

**Issue by suyashcjoshi** [joschuck/matrix-webcam#3]
Getting the following error when trying to install the pip package for this app on Apple M1 Mac:

```
OpenCV: not authorized to capture video (status 0), requesting...
Traceback (most recent call last):initialize!
  File "/opt/homebrew/bin/matrix-webcam", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/matrix_webcam/__main__.py", line 55, in main
    print(ascii_image(image, args.width, args.height))  # ascii image
  File "/opt/homebrew/lib/python3.9/site-packages/matrix_webcam/__main__.py", line 13, in ascii_image
    image = cv2.resize(image, (width, height))
cv2.error: OpenCV(4.6.0) /Users/xperience/actions-runner/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

```

**Comment by omyno** [comment]
Did you try to call the program with `sudo`?

**Comment by joschuck** [comment]
not sure why it goes for version 4.6.0 instead of 4.5.x 
another reason is maybe that terminal does not have the access right to your webcam due to Mac OS security settings?

**Comment by suyashcjoshi** [comment]
Think it was an access issue as after prefixing 'sudo' it worked
