### ISSUE TITLE
`mediapipe` fails to install on Apple Silicon

### ISSUE THREAD

**Issue by chanana** [joschuck/matrix-webcam#4]
When I do:
```shell
python -m pip install .
```

I get:
```shell
Processing /Users/chanana/code/investigations/webcam2
  Preparing metadata (setup.py) ... done
Collecting numpy~=1.20
  Using cached numpy-1.23.3-cp39-cp39-macosx_11_0_arm64.whl (13.4 MB)
Collecting opencv-contrib-python~=4.5.4
  Using cached opencv_contrib_python-4.5.5.64-cp37-abi3-macosx_11_0_arm64.whl (38.7 MB)
ERROR: Could not find a version that satisfies the requirement mediapipe~=0.8 (from matrix-webcam) (from versions: none)
ERROR: No matching distribution found for mediapipe~=0.8
```

My machine is an M1 MacBookPro with macOS 12.6

**Comment by chanana** [comment]
I tried the following and it worked for me:

Change [line 36](https://github.com/joschuck/matrix-webcam/blob/2f074cb1cf0760df84021fe85fcfab75ee292440/setup.py#L36) of `setup.py` to:

```python
'mediapipe~=0.8; platform_system != "Darwin" and platform.machine != "arm64"',
```

It's directly from [this issue](https://github.com/google/mediapipe/issues/3277).

After this, doing `python -m pip install .` as given in instructions works!

**Comment by joschuck** [comment]
actually that was fixed this morning in version 0.4.1 :) See #2 

Try `pip install matrix-webcam --upgrade`

**Comment by chanana** [comment]
I don't think it was fully fixed. Your fix only modified _one_ of the two lines required:

```python
mediapipe>=0.8.9; platform_system != "Darwin" and platform.machine != 'arm64'
mediapipe-silicon>=0.8.9; platform_system == "Darwin" and platform.machine == 'arm64'
```
Is the fix. [Your version](https://github.com/joschuck/matrix-webcam/blob/2f074cb1cf0760df84021fe85fcfab75ee292440/setup.py#L35) currently reads:

```python
'mediapipe-silicon~=0.8; platform_system=="Darwin" and platform.machine=="arm64"',
'mediapipe~=0.8',
```

`mediapipe` must also contain the conditional statements to avoid trying to install it on Apple Silicon systems

**Comment by joschuck** [comment]
just guessing here, but this would break on a let's say a Raspberry/Linux arm64 machine

**Comment by joschuck** [comment]
@chanana  check [v0.4.2](https://github.com/joschuck/matrix-webcam/releases/tag/v0.4.2)

**Comment by chanana** [comment]
Worked for me! Thank you!

**Comment by anikitin-intermedia** [comment]
I'm getting this crash after running matrix-webcam v0.4.2 on M1 Pro:
```
objc[25534]: Class CaptureDelegate is implemented in both /opt/homebrew/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x1057ee490) and /opt/homebrew/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_videoio.3.4.16.dylib (0x10901c860). One of the two will be used. Which one is undefined.
objc[25534]: Class CVWindow is implemented in both /opt/homebrew/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x1057ee4e0) and /opt/homebrew/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x108048a68). One of the two will be used. Which one is undefined.
objc[25534]: Class CVView is implemented in both /opt/homebrew/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x1057ee508) and /opt/homebrew/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x108048a90). One of the two will be used. Which one is undefined.
objc[25534]: Class CVSlider is implemented in both /opt/homebrew/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x1057ee530) and /opt/homebrew/lib/python3.10/site-packages/mediapipe/.dylibs/libopencv_highgui.3.4.16.dylib (0x108048ab8). One of the two will be used. Which one is undefined.
Add a python dependency on "@com_google_protobuf//:protobuf_python"
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZN6google8protobuf15FieldDescriptor12TypeOnceInitEPKS1_)
Traceback (most recent call last):
  File "/opt/homebrew/bin/matrix-webcam", line 5, in <module>
    from matrix_webcam.__main__ import main
  File "/opt/homebrew/lib/python3.10/site-packages/matrix_webcam/__main__.py", line 13, in <module>
    from mediapipe.python.solutions.selfie_segmentation import SelfieSegmentation
  File "/opt/homebrew/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/opt/homebrew/lib/python3.10/site-packages/mediapipe/python/__init__.py", line 28, in <module>
    import mediapipe.python.packet_getter
  File "/opt/homebrew/lib/python3.10/site-packages/mediapipe/python/packet_getter.py", line 20, in <module>
    from google.protobuf import symbol_database
  File "/opt/homebrew/lib/python3.10/site-packages/google/protobuf/symbol_database.py", line 62, in <module>
    from google.protobuf import descriptor_pool
  File "/opt/homebrew/lib/python3.10/site-packages/google/protobuf/descriptor_pool.py", line 63, in <module>
    from google.protobuf import descriptor
  File "/opt/homebrew/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZN6google8protobuf15FieldDescriptor12TypeOnceInitEPKS1_)
```

Could you help me with it?

**Comment by chanana** [comment]
What were your steps to set it up? It seems like you're using `python3.10`, perhaps you could try `3.9.13` instead and see if it still fails? I think using an older version of the `protobuf` library (by using py3.9) might help but that's just a guess

**Comment by anikitin-intermedia** [comment]
@chanana Thanks! `python 3.9.13` helps me.
